# main app 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: pawel2233/blog-app-nv:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
          - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-svc
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
    - port: 80
      targetPort: 5001
      nodePort: 300
